Repository jupyter-naas/awesome-notebooks, pull requests merged in 2022-03, with the labels that each got.

#338 feat: Excel custom sheet
  Excel/Excel_Custom_sheet.ipynb
  Excel/Excel_Get_dynamic_active_range.ipynb
  Excel/Excel_Template.xlsx
Labels: good first issue

#333 fix: google analytics final tunning
  Google Analytics/GoogleAnalytics_Get_bounce_rate.ipynb
  Google Analytics/GoogleAnalytics_Get_pageview_ranking.ipynb
  Google Analytics/GoogleAnalytics_Get_stats_per_country.ipynb
  Google Analytics/GoogleAnalytics_Get_time_on_landing_page.ipynb
  Google Analytics/GoogleAnalytics_Get_unique_visitors.ipynb
Labels: enhancement

#357 ci: Add notebook lint on pull request
  .github/Dockerfile
  .github/controls/check_notebooks.ipynb
  .github/requirements.txt
  .github/workflows/lint_notebooks.yaml
  .gitignore
  Makefile
Labels: enhancement

#366 feat: Documentation auto update
  .github/documentation/documentation_update.ipynb
  .github/requirements.txt
  .github/workflows/update_documentation.yaml
  .gitignore
  Makefile
Labels: documentation

#371 fix: slack post jobs
  Remoteok/Remoteok_Post_daily_jobs_on_slack.ipynb
Labels: bug
