Repository jupyter-naas/awesome-notebooks, pull requests merged in 2023-05, with the labels that each got.

#1734 feat: BeautifulSoup - List social network links from website
  BeautifulSoup/BeautifulSoup_List_social_network_links_from_website.ipynb
Labels: good first issue

#1736 feat: Naas - Find Asset link from path
  Naas/Naas_Find_Asset_link_from_path.ipynb
Labels: good first issue

#1658 feat: Python - Download ZIP from URL
  Python/Python_Download_ZIP_from_URL.ipynb
Labels: good first issue

#1738 feat: Python - Get next occurrences of a cron job
  Python/Python_Get_next_occurrences_of_a_cron_job.ipynb
Labels: good first issue

#1742 feat: Python - Set variables in environment
  Python/Python_Access_environment_variable.ipynb
  Python/Python_Add_new_environment_variable.ipynb
  Python/Python_Get_access_of_environment_variables.ipynb
Labels: good first issue

#1706 feat: Vizzu - Create Animated Pie Chart
  Vizzu/Vizzu_Create_Animated_Pie_Chart.ipynb
Labels: good first issue

#1712 feat: HubSpot - Send sales pipeline to Notion
  HubSpot/HubSpot_Get_all_pipelines_and_dealstages.ipynb
  HubSpot/HubSpot_Send_sales_pipeline_to_Notion.ipynb
Labels: good first issue

#1754 feat: Gmail - Send email
  Gmail/Gmail_Send_email.ipynb
Labels: good first issue

#1642 feat: Clockify - Remove user from workspace
  Clockify/Clockify_Remove_user_from_workspace.ipynb
Labels: good first issue

#1759 feat: Clockify - Find all users on workspace
  Clockify/Clockify_Find_all_users_on_workspace.ipynb
Labels: good first issue

#1761 feat: Clockify - Find clients on workspace
  Clockify/Clockify_Find_all_users_on_workspace.ipynb
  Clockify/Clockify_Find_clients_on_workspace.ipynb
Labels: templates maintainer

#1765 feat: Clockify - Find tasks on project
  Clockify/Clockify_Find_tasks_on_project.ipynb
  Clockify/Clockify_Get_all_projects_on_workspace.ipynb
Labels: good first issue, templates maintainer

#1763 feat: Clockify - CRUD client
  Clockify/Clockify_Add_a_new_client.ipynb
  Clockify/Clockify_Delete_client.ipynb
  Clockify/Clockify_Get_client_by_ID.ipynb
  Clockify/Clockify_Update_client.ipynb
Labels: good first issue, templates maintainer

#1769 feat: Clockify - Get time entries for a user on workspace
  Clockify/Clockify_Get_time_entries_for_a_user_on_workspace.ipynb
Labels: good first issue, templates maintainer

#1732 feat: Stripe - Create a customer
  Stripe/Stripe_Create_a_customer.ipynb
  Stripe/Stripe_Delete_a_customer.ipynb
  Stripe/Stripe_Get_customers.ipynb
  Stripe/Stripe_List_all_customers.ipynb
  Stripe/Stripe_Retrieve_a_customer.ipynb
  Stripe/Stripe_Update_a_customer.ipynb
Labels: good first issue

#1777 feat: Gmail - Create GitHub issue on specific email
  Gmail/Gmail_Automate_response_from_keywords_in_mailbox.ipynb
  Gmail/Gmail_Create_GitHub_issue_on_specific_email.ipynb
Labels: templates maintainer

#1767 feat: Gmail - Create draft email
  Gmail/Gmail_Create_draft_email.ipynb
Labels: templates maintainer

#1791 feat: Python - Calculate time delta between two dates
  Python/Python_Calculate_relative_time_delta_between_two_dates.ipynb
  Python/Python_Calculate_time_delta_between_two_dates.ipynb
  Python/Python_Convert_relative_time_delta_to_months.ipynb
  Python/Python_Convert_time_delta_to_months.ipynb
Labels: templates maintainer

#1792 feat: Compress images
  Python/Python_Compress_images.ipynb
Labels: good first issue

#1747 feat: Advertools - Analyze website content using XML sitemap
  Advertools/Advertools_Analyze_website_content_using_XML_sitemap.ipynb
Labels: good first issue

#1797 feat: Naas - Add or Update Dependency
  Naas/Naas_Add_or_Update_Asset.ipynb
  Naas/Naas_Add_or_Update_Dependency.ipynb
  Naas/Naas_Add_or_Update_Scheduler.ipynb
  Naas/Naas_Add_or_Update_Secret.ipynb
  Naas/Naas_Add_or_Update_Webhook.ipynb
  Naas/Naas_Delete_Dependency.ipynb
  Naas/Naas_List_Dependencies.ipynb
Labels: templates maintainer

#1794 feat: FEC - Visualiser Charges Horizontal Barchart
  FEC/FEC_Visualiser_Charges_Horizontal_Barchart.ipynb
Labels: templates maintainer

#1799 feat: Dash - Create conditional formatting of an HTML element
  Dash/Dash_Create_conditional_formatting_on_HTML_element.ipynb
  Dash/Dash_Create_conditional_formatting_on_number_value.ipynb
Labels: templates maintainer

#1801 feat: FEC - Lecture des fichiers
  FEC/FEC_Lecture_des_fichiers.ipynb
Labels: templates maintainer

#1802 feat: generate text summaries
  OpenAI/OpenAI_Generate_text_summaries.ipynb
Labels: good first issue

#1818 feat: OpenAI - Act as a chef
  OpenAI/OpenAI_Act_as_a_chef.ipynb
Labels: templates maintainer

#1824 feat: Python - List specific files from directory and subdirectories
  Python/Python_List_specific_files_from_directory_and_subdirectories.ipynb
Labels: templates maintainer

#1779 feat: Added extract chat from whatsapp
  WhatsApp/WhatsApp_Transform_chat_txt_to_dataframe.ipynb
Labels: good first issue

#1756 feat: OpenAI - Create chat completion
  OpenAI/OpenAI_Create_chat_completion.ipynb
Labels: good first issue

#1828 feat: OpenAI - Create chat conversation with OpenAI
  OpenAI/OpenAI_Create_Completion.ipynb
  OpenAI/OpenAI_Create_chat_completion.ipynb
  OpenAI/OpenAI_Create_chat_conversation_with_OpenAI.ipynb
Labels: templates maintainer
