Repository jupyter-naas/awesome-notebooks, pull requests merged in 2023-07, with the labels that each got.

#1840 feat: LangChain - JSON Agent
  LangChain/LangChain_JSON_Agent.ipynb
Labels: good first issue

#1682 feat: Pydub - Convert audio file M4A to MP3
  MoviePy/MoviePy_Convert_audio_file_M4A_to_MP3.ipynb
  Python/Python_Download_Image_from_URL.ipynb
  Python/Python_Download_audio_file_from_URL.ipynb
Labels: good first issue

#1984 fix: update deprecated library + remove asset file
  PDF/Installation_Guide.pdf
  PDF/PDF_Extract_Text_from_PDF.ipynb
Labels: bug

#1992 feat: OS - Get folder stats
  OS/OS_Get_folder_stats.ipynb
Labels: templates maintainer

#1994 feat: Datetime - Convert timestamp to a datetime object
  CSV/CSV_Read_file.ipynb
  CSV/CSV_Save_file.ipynb
  Datetime/Datetime_Calculate_relative_time_delta_between_two_dates.ipynb
  Datetime/Datetime_Calculate_time_delta_between_two_dates.ipynb
  Datetime/Datetime_Convert_datetime_object_to_string_date.ipynb
  Datetime/Datetime_Convert_datetime_with_timezone_to_ISO_8601_date_string.ipynb
  Datetime/Datetime_Convert_relative_time_delta_to_months.ipynb
  Datetime/Datetime_Convert_string_to_datetime_object.ipynb
  Datetime/Datetime_Convert_timestamp_to_a_datetime_object.ipynb
Labels: templates maintainer

#1838 feat: LangChain - Gmail Toolkit
  LangChain/LangChain_Gmail_Toolkit.ipynb
Labels: enhancement, templates maintainer

#1966 feat: GitHub - Send templates created on a notebooks to Slack channel
  GitHub/GitHub_Send_templates_created_on_a_notebooks_to_Slack_channel.ipynb
Labels: enhancement

#2011 feat: Agicap - Get bank account from company
  Agicap/Agicap_Get_banks_accounts_from_company.ipynb
  Agicap/Agicap_List_companies.ipynb
Labels: templates maintainer

#1666 feat: Trello - List Boards
  Trello/Trello_List_Boards.ipynb
Labels: good first issue

#2014 feat: Agicap - Export categories from company
  Agicap/Agicap_Get_inflow_categories_from_company.ipynb
  Agicap/Agicap_Get_outflow_categories_from_company.ipynb
Labels: templates maintainer

#1974 feat: Trello - Get Cards on a Board
  GitHub/GitHub_Clone_repository_and_switch_branch.ipynb
  Trello/Trello_Get_Cards_on_a_Board.ipynb
Labels: good first issue

#1971 feat: Trello - Retrieve List ID
  Trello/Trello_Get_Lists_on_a_Board.ipynb
Labels: enhancement

#1668 feat: Trello - Create Card
  Trello/Trello_Create_Card.ipynb
Labels: good first issue

#1721 feat: Azure Blob Storage - List blobs
  Azure Blob Storage/Azure_Blob_Storage_List_blobs.ipynb
Labels: good first issue

#1727 feat: Azure Machine Learning - Univariate Timeseries Inference
  Azure Machine Learning/Azure_Machine_Learning_Univariate_Timeseries_Inference.ipynb
Labels: good first issue

#2000 feat: Mixpanel - Get Profile Event Activity
  Mixpanel/Mixpanel_Get_Profile_Event_Activity.ipynb
Labels: templates maintainer

#2019 2015 gmail most common senders
  Gmail/Gmail_Get_most_common_senders.ipynb
Labels: good first issue

#1857 1854 advertools bulk status code checker with response headers
  .github/controls/check_notebooks.ipynb
  Advertools/Advertools_Analyze_website_content_using_XML_sitemap.ipynb
  Advertools/Advertools_Audit_robots_txt_and_xml_sitemap_issues.ipynb
  Advertools/Advertools_Check_status_code_and_Send_notifications.ipynb
  Advertools/Advertools_Check_status_code_in_bulk.ipynb
  Advertools/Advertools_Visualize_status_codes_OK_KO.ipynb
  Advertools/Advertools_Visualize_status_codes_count.ipynb
Labels: bug, enhancement

#2002 2001 gmail mark emails as seen
  Gmail/Gmail_Mark_emails_as_seen_by_dates.ipynb
Labels: good first issue

#1979 feat: GitHub - Get DataFrame from project view
  GitHub/GitHub_Get_DataFrame_with_issue_estimate_from_project_view.ipynb
Labels: templates maintainer

#2042 feat: Pandas - Format URL as clickable link on column
  Pandas/Pandas_Format_URL_as_clickable_link_on_column.ipynb
Labels: templates maintainer

#1969 feat: LinkedIn chat about my latest profile posts
  LinkedIn/LinkedIn_Chat_about_my_lastest_profile_posts.ipynb
Labels: enhancement

#2049 feat: Polars - Concatenate DataFrames
  Polars/Polars_Concatenate_DataFrames.ipynb
Labels: templates maintainer

#2051 feat: Python - Check if string is number
  Python/Python_Check_if_string_is_number.ipynb
Labels: templates maintainer

#2053 feat: Python - Convert string boolean to boolean
  Python/Python_Convert_string_boolean_to_boolean.ipynb
Labels: templates maintainer

#2040 feat: Pandas - Apply custom styles on column
  Pandas/Pandas_Apply_custom_styles_on_column.ipynb
Labels: templates maintainer

#2063 2059 improve notebook templates
  LinkedIn/LinkedIn_Chat_about_my_latest_profile_posts.ipynb
  LinkedIn/LinkedIn_Get_connections_from_network.ipynb
Labels: enhancement

#2007 2006 google maps routes api geocoding
  Google Maps/Google_Maps_Get_coordinates_from_address.ipynb
Labels: good first issue

#2009 2008 google maps routes api calculate the toll costs for a given route
  Google Maps/Google_Maps_Calculate_travel_costs_between_two_addresses.ipynb
Labels: good first issue

#1771 feat: Clockify - Create time entries database for a user on workspace
  Clockify/Clockify_Create_time_entries_database_on_workspace.ipynb
Labels: templates maintainer

#2065 feat: OpenAlex - Get lists of authors
  OpenAlex/OpenAlex_Get_lists_of_authors.ipynb
  OpenAlex/OpenAlex_Get_lists_of_concepts.ipynb
  OpenAlex/OpenAlex_Get_lists_of_funders.ipynb
  OpenAlex/OpenAlex_Get_lists_of_institutions.ipynb
  OpenAlex/OpenAlex_Get_lists_of_publishers.ipynb
  OpenAlex/OpenAlex_Get_lists_of_sources.ipynb
  OpenAlex/OpenAlex_Get_lists_of_works.ipynb
Labels: templates maintainer

#2026 2025 google sheet calculate distance and price
  Google Sheets/Google_Sheets_Calculate_Distance_and_Price.ipynb
Labels: enhancement, good first issue

#2079 feat: JSON - Convert Python Objects to JSON
  JSON/JSON_Convert_Python_Objects_to_JSON.ipynb
  JSON/JSON_Save_dataframe_to_JSON_file.ipynb
  JSON/JSON_Send_to_Google_Sheets_spreadsheet.ipynb
Labels: templates maintainer

#2081 feat: JSON - Pretty Print JSON Data
  JSON/JSON_Pretty_print_JSON_data.ipynb
Labels: templates maintainer
