Repository jupyter-naas/awesome-notebooks, pull requests merged in 2023-02, with the labels that each got.

#1433 Fix: Generate README workflow
  .github/workflows/generate_readme.yaml
Labels: bug, enhancement

#1447 feat(Python): Add Check email validity
  Python/Python_Check_email_validity.ipynb
Labels: enhancement

#1448 feat: beautifulsoup scrape emails from URL
  BeautifulSoup/BeautifulSoup_Scrape_emails_from_URL.ipynb
Labels: enhancement

#1455 feat(SWIFT): Add Create MT940 XML file
  SWIFT/SWIFT_Create_MT940_XML_file.ipynb
Labels: enhancement

#1439 feat: bitly create links
  Bitly/Bitly_Create_Links.ipynb
Labels: enhancement

#1442 feat: bitly list active links
  Bitly/Bitly_Retrieve_Bitlink.ipynb
Labels: enhancement

#1484 OpenAI - Write a blog post
  OpenAI/OpenAI_Write_a_blog_post.ipynb
Labels: good first issue

#1486 OpenAI - Write a social media post
  OpenAI/OpenAI_Write_a_social_media_post.ipynb
Labels: good first issue

#1488 OpenAI - Write a press release
  OpenAI/OpenAI_Write_a_press_release.ipynb
Labels: good first issue

#1490 OpenAI - Brainstorm ideas
  OpenAI/OpenAI_Brainstorm_ideas.ipynb
Labels: good first issue

#1492 OpenAI - Write an outline
  OpenAI/OpenAI_Write_an_outline.ipynb
Labels: good first issue

#1471 Python - Get last file modified from directy
  Python/Python_Get_last_file_modified_from_directy.ipynb
Labels: good first issue

#1494 OpenAI - Write a job description
  OpenAI/OpenAI_Write_a_job_description.ipynb
Labels: good first issue

#1463 feat(GitHub): Add Get Closed PR by repo
  GitHub/GitHub_Get_Closed_PR_by_repo.ipynb
Labels: good first issue

#1467 feat(Abstract API): Add Check Email Validation
  Abstract API/Abstract_API_Check_Email_Validation.ipynb
  Abstract API/Abstract_API_Get_IP_Geolocation.ipynb
Labels: good first issue

#1496 feat: GitHub - Get files added on Pull Request Merged
  GitHub/GitHub_Get_files_added_on_Pull_Request_Merged.ipynb
Labels: good first issue

#1424 1318 GitHub create leaderboard of contributors
  GitHub/GitHub_Create_leaderboard_of_contributors.ipynb
Labels: enhancement

#1427 Added: Supabase Email Authentication
  Supabase/Supabase_Email_Auth.ipynb
Labels: enhancement

#1277 added create template link yaml file
  .github/workflows/create_link_to_template.yaml
Labels: documentation

#1482 StabiltyAI - Generate PNG file from prompt
  Stabilty AI/Stabilty_AI_Generate_Image_from_text.ipynb
Labels: good first issue

#1519 feat: ZeroBounce - Validate Single Email
  ZeroBounce/ZeroBounce_Validate_Single_Email.ipynb
Labels: good first issue

#1521 feat: Python - Create Email Combination with Firstname, Lastname, Domain address
  Python/Python_Create_Email_Combination_with_Firstname_Lastname_Domain_address.ipynb
Labels: good first issue

#1502 feat: Bitly - Delete a Bitlink
  Bitly/Bitly_Delete_a_Bitlink.ipynb
Labels: good first issue

#1504 feat: Bitly - Update a Bitlink
  Bitly/Bitly_Update_a_Bitlink.ipynb
Labels: good first issue

#1513 feat: Bitly - Get Metrics for a Bitlink by Referrers
  Bitly/Bitly_Get_Metrics_for_a_Bitlink_by_Referrers.ipynb
Labels: good first issue

#1474 Bitly - Get a Clicks Summary for a Bitlink
  Bitly/Bitly_Get_a_Clicks_Summary_for_a_Bitlink.ipynb
Labels: good first issue

#1476 Bitly - Get Metrics for a Bitlink by Country
  Bitly/Bitly_Get_Metrics_for_a_Bitlink_by_Country.ipynb
Labels: good first issue

#1511 feat: Bitly - Get Metrics for a Bitlink by Device Type
  Bitly/Bitly_Get_Metrics_for_a_Bitlink_by_Devices.ipynb
Labels: good first issue

#1509 feat: Bitly - Get Clicks for a Bitlink
  Bitly/Bitly_Get_Clicks_for_a_Bitlink.ipynb
Labels: good first issue

#1507 feat: Bitly - Get Metrics for a Bitlink by City
  Bitly/Bitly_Get_Metrics_for_a_Bitlink_by_City.ipynb
Labels: good first issue
