Repository jupyter-naas/awesome-notebooks, pull requests merged in 2023-08, with the labels that each got.

#2104 feat: LinkedIn - Send like to post
  LinkedIn/LinkedIn_Send_like_to_post.ipynb
Labels: templates maintainer

#2100 feat: Advertools - Check website pages status code
  Advertools/Advertools_Check_website_pages_status_code.ipynb
Labels: templates maintainer

#2070 2020 google maps routes api route optimisation
  Google Maps/Google_Maps_Create_itinerary_optimisation_on_differents_waypoints.ipynb
Labels: enhancement, good first issue

#2067 Google Maps - Create and display distance matrix
  Google Maps/Google_Maps_Create_and_display_distance_matrix.ipynb
Labels: enhancement, good first issue

#2128 fix: Update generate_readme.ipynb
  generate_readme.ipynb
Labels: bug

#2107 feat: LinkedIn - Send like to latest profile post
  LinkedIn/LinkedIn_Send_like_to_latest_profile_post.ipynb
Labels: templates maintainer

#2118 feat: HubSpot - Manage meetings
  HubSpot/HubSpot_Get_meetings_associated_to_contact.ipynb
  HubSpot/HubSpot_List_meeting_properties.ipynb
  HubSpot/HubSpot_Retrieve_meetings.ipynb
Labels: templates maintainer

#2030 feat: HubSpot - List communications from contact
  HubSpot/HubSpot_Add_LinkedIn_message_to_contact.ipynb
  HubSpot/HubSpot_Add_SMS_message_to_contact.ipynb
  HubSpot/HubSpot_Add_WhatsApp_message_to_contact.ipynb
  HubSpot/HubSpot_Delete_communication.ipynb
  HubSpot/HubSpot_Get_communications_associated_to_contact.ipynb
  HubSpot/HubSpot_List_communication_properties.ipynb
  HubSpot/HubSpot_Retrieve_communication_details.ipynb
Labels: templates maintainer

#2167 feat: Python - Get emojis from text
  Python/Python_Get_emojis_from_text.ipynb
Labels: good first issue

#2176 feat: Python - Remove HTML tags from text
  RegEx/RegEx_Remove_HTML_tags_from_text.ipynb
Labels: good first issue

#2186 feat: Python - Calculate the percentage of similarity between two strings
  Python/Python_Calculate_the_percentage_of_similarity_between_two_strings.ipynb
Labels: good first issue
