Repository jupyter-naas/awesome-notebooks, pull requests merged in 2023-06, with the labels that each got.

#1832 feat: Naas - List Schedulers
  Naas/Naas_List_Schedulers.ipynb
  Naas/Naas_List_Schedulers_with_all_executions.ipynb
  Naas/Naas_List_Schedulers_with_last_execution.ipynb
Labels: templates maintainer

#1834 feat: LangChain - Pandas Dataframe Agent
  LangChain/LangChain_Pandas_Dataframe_Agent.ipynb
Labels: templates maintainer

#1842 feat: Dash - Create loading button
  Dash/Dash_Create_loading_button.ipynb
Labels: good first issue

#1848 feat: Dash - Create download button
  Dash/Dash_Create_download_button.ipynb
  Dash/Dash_Create_spinner_button.ipynb
Labels: good first issue

#1826 feat: Naas - Send image asset to Notion page
  Naas/Naas_Send_Asset_image_to_Notion_page.ipynb
Labels: templates maintainer

#1856 feat: Dash - Add a customisable sidebar
  Dash/Dash_Add_a_customisable_sidebar.ipynb
Labels: good first issue

#1751 feat: Stable Diffusion - Generate image from text
  Stable Diffusion/Stable_Diffusion_Generate_image_from_text.ipynb
Labels: good first issue

#1895 feat: OS - List entries in directory
  OS/OS_List_entries_in_directory.ipynb
Labels: enhancement

#1908 feat: Python - Find differences between stings
  Python/Python_Find_differences_between_stings.ipynb
Labels: good first issue

#1905 feat: Pandas - Get n smallest
  Pandas/Pandas_Get_n_smallest.ipynb
Labels: good first issue

#1903 feat: Pandas - Get n largest
  Pandas/Pandas_Get_n_largest.ipynb
Labels: good first issue

#1920 feat: Algolia - Get all records from an index
  Algolia/Algolia_Add_or_Replace_all_attributes_in_existing_records.ipynb
  Algolia/Algolia_Add_or_Replace_all_attributes_in_single_record.ipynb
  Algolia/Algolia_Delete_multiples_objects.ipynb
  Algolia/Algolia_Delete_single_object.ipynb
  Algolia/Algolia_Get_all_records_from_an_index.ipynb
  Algolia/Algolia_List indices.ipynb
Labels: good first issue

#1882 feat: Request - Basic HTTP GET Request
  Request/Request_Basic_HTTP_GET_Request.ipynb
Labels: good first issue

#1884 feat: Request - Sending POST Requests with Data
  Request/Request_Sending_POST_Requests_with_Data.ipynb
Labels: good first issue

#1900 feat: Pandas - Sort values by multiples columns
  Pandas/Pandas_Sort_values_by_multiples_columns.ipynb
Labels: good first issue

#1945 feat: OpenAI - Count tokens with tiktoken
  OpenAI/OpenAI_Count_tokens_with_tiktoken.ipynb
Labels: enhancement

#1912 feat: Harvest - List all clients
  Harvest/Harvest_List_all_clients.ipynb
Labels: good first issue

#1940 feat: Python - Manage exception with try except
  Python/Python_Manage_exception_with_try_except.ipynb
Labels: good first issue

#1951 feat: add #plugin in tags
  OpenAI/OpenAI_Act_as_a_chef.ipynb
  generate_readme.ipynb
Labels: enhancement

#1928 feat: Python - Create Secure Hash Algorithm
  Python/Python_Transform_string_to_Secure_Hash_Algorithm.ipynb
Labels: good first issue

#1931 feat: Python - Get a random word
  Python/Python_Get_random_word.ipynb
Labels: good first issue

#1892 fix: Issues in Stable diffusion generate images template
  Stable Diffusion/Stable_Diffusion_Generate_image_from_text.ipynb
Labels: bug, enhancement

#1936 feat: Python - Pseudonym generator
  Python/Python_Pseudonym_generator.ipynb
Labels: good first issue

#1943 feat: Python - Unit converter
  Python/Python_Convert_units.ipynb
Labels: good first issue

#1259 1235 generate contribution certificate when pr is merged
  .github/workflows/generate_certificate.yaml
  certificate-template.png
  generate_certificate.py
Labels: enhancement

#1517 feat: Shutterstock - Search for images
  Shutterstock/Shutterstock_Search_for_images.ipynb
Labels: good first issue

#1576 Twilio: Send SMS for Google Calendar events
  Twilio/Twilio_Send_SMS_Google_Calendar_Events.ipynb
Labels: good first issue

#1952 feat: Slack - Send blocks to channel
  Slack/Slack_Send_blocks_to_channel.ipynb
  Slack/Slack_Send_message_to_channel.ipynb
Labels: enhancement

#1960 feat: convert multiple units
  Python/Python_Convert_length.ipynb
  Python/Python_Convert_speed.ipynb
  Python/Python_Convert_temperature.ipynb
  Python/Python_Convert_time.ipynb
  Python/Python_Convert_volume.ipynb
  Python/Python_Convert_weight.ipynb
Labels: good first issue

#1886 feat: Request - Handling Errors and Exceptions
  Request/Request_Handling_Errors_and_Exceptions.ipynb
Labels: good first issue

#1955 feat: GitHub - List branches
  GitHub/GitHub_List_branches.ipynb
  GitHub/GitHub_List_branches_with_open_PR.ipynb
Labels: good first issue

#1961 feat: GitHub send contributor activity on slack
  GitHub/GitHub_Send_contributor_activity_on_slack.ipynb
Labels: enhancement
