Repository jupyter-naas/awesome-notebooks, pull requests merged in 2023-12, with the labels that each got.

#2419 2408 spotify get artist
  Spotify/Spotify_Get_Artist.ipynb
Labels: enhancement

#2433 feat: RegEx - Remove emojis from text
  RegEx/RegEx_Remove_emojis_from_text.ipynb
  template.ipynb
Labels: good first issue

#2430 2420 spotify get album
  Spotify/Spotify_Get_Album.ipynb
Labels: good first issue

#2435 2422 spotify get new releases
  Spotify/Spotify_Get_New_Releases.ipynb
Labels: good first issue

#2445 feat(Spotify): Get artist's albums
  Spotify/Spotify_Get_Artist_Albums.ipynb
Labels: good first issue

#2446 feat(Spotify): Get artist's top 10 tracks
  Spotify/Spotify_Get_Artists_Top_Tracks.ipynb
Labels: good first issue

#2456 fix(Spotify): Names for templates
  Spotify/Spotify_Get_Artist_Albums.ipynb
  Spotify/Spotify_Get_Artists_Top_Tracks.ipynb
Labels: bug

#2454 feat(Spotify): Get related artists
  Spotify/Spotify_Get_Artist_Related_Artists.ipynb
Labels: good first issue

#2438 feat: LinkedIn - Get profile top card
  LinkedIn/LinkedIn_Get_profile_top_card.ipynb
Labels: enhancement

#2465 feat: LinkedIn - Get post interactions
  LinkedIn/LinkedIn_Get_post_comments_profiles.ipynb
  LinkedIn/LinkedIn_Get_post_interactions.ipynb
  LinkedIn/LinkedIn_Get_post_likes_profiles.ipynb
  generate_readme.ipynb
Labels: enhancement

#2467 feat(Spotify): Get user top items
  Spotify/Spotify_Get_User_Top_Items.ipynb
Labels: good first issue
