Repository jupyter-naas/awesome-notebooks, pull requests merged in 2023-09, with the labels that each got.

#2204 feat: Agicap - Get transactions by account
  Agicap/Agicap_Get_transactions_by_account.ipynb
Labels: enhancement

#2172 feat: HubSpot - Chat about HubSpot contact activities
  HubSpot/HubSpot_Chat_about_a_contact.ipynb
  HubSpot/HubSpot_Get_contact_brief.ipynb
  HubSpot/HubSpot_Get_deal_brief.ipynb
Labels: enhancement

#2180 feat: HubSpot - Create company
  HubSpot/HubSpot_Create_company.ipynb
  HubSpot/HubSpot_Delete_company.ipynb
  HubSpot/HubSpot_Get_company.ipynb
  HubSpot/HubSpot_Update_company.ipynb
Labels: good first issue

#2221 feat: IPython - Display dynamic link in Jupyter Lab
  IPython/IPython_Display_dynamic_link_in_Jupyter_Lab.ipynb
Labels: good first issue

#2012 Langchain vector search PDF
  LangChain/LangChain_Vector_Search_on_PDF.ipynb
Labels: enhancement, templates maintainer

#2215 feat: OpenAI - Create Naas Chat plugin
  HubSpot/HubSpot_Chat_about_a_deal.ipynb
  Naas Chat Plugin/Naas_Chat_Plugin_Check_prompt_tokens.ipynb
  Naas Chat Plugin/Naas_Chat_Plugin_Count_prompt_tokens.ipynb
  Naas Chat Plugin/Naas_Chat_Plugin_Create_prompt_plugin.ipynb
  Naas Chat Plugin/Naas_Chat_Plugin_Create_prompt_plugin_with_command.ipynb
  OpenAI/OpenAI_Act_as_a_School_Teacher.ipynb
  OpenAI/OpenAI_Create_Act_as_plugin.ipynb
Labels: enhancement
