Repository jupyter-naas/awesome-notebooks, pull requests merged in 2023-11, with the labels that each got.

#2338 feat: ImagineAPI.dev - Create Image
  ImagineAPI.dev/ImagineAPI.dev_Create_Image.ipynb
  ImagineAPI.dev/ImagineAPI.dev_Get_Image.ipynb
  ImagineAPI.dev/ImagineAPI.dev_List_Images.ipynb
Labels: enhancement, hacktoberfest

#2331 2257 google sheets create new sheet
  Google Sheets/Google_Sheets_Create_new_sheet.ipynb
Labels: enhancement, hacktoberfest

#2358 feat: add linkedin logo in templates.json
  ImagineAPI/ImagineAPI_Create_Image.ipynb
  ImagineAPI/ImagineAPI_Get_Image.ipynb
  ImagineAPI/ImagineAPI_List_Images.ipynb
  generate_readme.ipynb
Labels: enhancement

#2361 feat: add LinkedIn and Naas logo
  .github/assets/logos/LinkedIn.png
  .github/assets/logos/Naas.png
Labels: enhancement

#2362 feat: update logo size to 8%
  .github/assets/logos/Advertools.png
  .github/assets/logos/Azure Blob Storage.png
  .github/assets/logos/Azure Machine Learning.jpg
  .github/assets/logos/BeautifulSoup.png
  .github/assets/logos/Dash.png
  .github/assets/logos/Excel.png
  .github/assets/logos/Faker.png
  .github/assets/logos/Folium.jpg
  .github/assets/logos/Folium.png
  .github/assets/logos/Geopy.png
  .github/assets/logos/JSON.png
  .github/assets/logos/Panel.png
  .github/assets/logos/PyPI.jpeg
  .github/assets/logos/Python.png
  .github/assets/logos/Pyvis.png
  .github/assets/logos/RegEx.png
  .github/assets/logos/Request.png
  PyPI/PyPI_Get_number_of_downloads_any_package.ipynb
  generate_readme.ipynb
Labels: enhancement

#2346 feat: Google Sheets - List sheets from spreadsheet
  Google Sheets/Google_Sheets_List_sheets_from_spreadsheet.ipynb
Labels: enhancement, hacktoberfest

#2348 feat: Google Sheets - Delete sheet from spreadsheet
  Google Sheets/Google_Sheets_Delete_sheet_from_spreadsheet.ipynb
Labels: enhancement, hacktoberfest

#2373 fix: 2372 linkedin get stats from post error retrieve repost
  .github/assets/logos/Google Analytics.png
  LinkedIn/LinkedIn_Generate_leads_from_posts.ipynb
  LinkedIn/LinkedIn_Get_post_comments_profiles.ipynb
  LinkedIn/LinkedIn_Get_post_likes_profiles.ipynb
  LinkedIn/LinkedIn_Get_post_poll_results.ipynb
  LinkedIn/LinkedIn_Get_post_stats.ipynb
Labels: bug

#2380 Update generate_readme.ipynb
  generate_readme.ipynb
Labels: bug

#2290 feat: Clockify - Send Daily Activity Brief to Slack
  Clockify/Clockify_Send_activity_brief_to_Slack.ipynb
Labels: enhancement, hacktoberfest

#2384 feat: Datetime - Get first and last day of the current week
  Datetime/Datetime_Get_first_and_last_day_of_the_current_week.ipynb
Labels: good first issue

#2386 feat: Datetime - Get first and last day of last week
  Datetime/Datetime_Get_first_and_last_day_of_last_week.ipynb
Labels: good first issue

#2388 feat: Datetime - Get weekday
  Datetime/Datetime_Get_the_weekday_of_the_current_date.ipynb
Labels: good first issue

#2394 feat: add template connections batch 2
  .github/assets/characters/None.png
  .github/assets/characters/None_1.png
  .github/assets/characters/None_2.png
  .github/assets/characters/None_3.png
  .github/assets/characters/Oprah Winfrey.png
  .github/assets/logos/Google Docs.png
  .github/assets/logos/JSON.jpg
  .github/assets/logos/JSON.png
  Algolia/Algolia_List indices.ipynb
  Algolia/Algolia_Setup_connection.ipynb
  Bitly/Bitly_Retrieve_Bitlink.ipynb
  Bitly/Bitly_Setup_connection.ipynb
  Clockify/Clockify_Get_time_entries_for_a_user_on_workspace.ipynb
  Clockify/Clockify_Setup_connection.ipynb
  Harvest/Harvest_List_all_time_entries.ipynb
  Harvest/Harvest_List_all_users.ipynb
  Harvest/Harvest_Setup_connection.ipynb
  Trello/Trello_Get_Cards_on_a_Board.ipynb
  Trello/Trello_Setup_connection.ipynb
Labels: enhancement

#2400 feat: Qdrant - Connect to client
  .github/assets/logos/Qdrant.jpeg
  .github/assets/logos/Worldometer.jpg
  Qdrant/Qdrant_Connect_to_cloud.ipynb
  Qdrant/Qdrant_Delete_collection.ipynb
  Qdrant/Qdrant_Get_collection.ipynb
  Qdrant/Qdrant_Get_collections.ipynb
  Qdrant/Qdrant_Setup_connection.ipynb
Labels: good first issue

#2403 feat: OpenAI - Use GPT-4
  .github/assets/logos/Meta.jpg
  Meta/Meta_Use_Llama2.ipynb
  OpenAI/OpenAI_Use_ChatGPT3.5_turbo.ipynb
  OpenAI/OpenAI_Use_ChatGPT3.5_turbo_16k.ipynb
  OpenAI/OpenAI_Use_ChatGPT4.ipynb
Labels: good first issue

#2405 feat: Mercury - Retrieve accounts
  .github/assets/logos/Mercury.jpeg
  Mercury/Mercury_Get_accounts.ipynb
  Mercury/Mercury_Get_transactions.ipynb
  Mercury/Mercury_Setup_connection.ipynb
  OpenAI/OpenAI_Create_chat_completion.ipynb
Labels: enhancement

#2391 Hugging Face - Token Classification for Sequence Labelling Tasks using Inference API
  Hugging Face/Hugging_Face_Token_Classification_for_Sequence_Labelling_Tasks_using_Inference_API.ipynb
Labels: enhancement
