Repository jupyter-naas/awesome-notebooks, pull requests merged in 2023-10, with the labels that each got.

#2232 feat: Google Drive - CRUD
  Google Drive/Google_Drive_Add_properties_to_file.ipynb
  Google Drive/Google_Drive_Create_folder.ipynb
  Google Drive/Google_Drive_Download_file.ipynb
  Google Drive/Google_Drive_Download_video_file.ipynb
  Google Drive/Google_Drive_List_folder.ipynb
  Google Drive/Google_Drive_Move_file.ipynb
  Google Drive/Google_Drive_Remove_file.ipynb
  Google Drive/Google_Drive_Retrieve_file_meta.ipynb
  Google Drive/Google_Drive_Retrieve_file_properties.ipynb
  Google Drive/Google_Drive_Upload_file.ipynb
Labels: enhancement

#2241 feat: GitHub create issue in repository from naas chat
  GitHub/GitHub_Connect_from_Naas_Chat.ipynb
  GitHub/GitHub_Create_Issue_from_Naas_Chat.ipynb
  GitHub/GitHub_Create_plugin_with_commands.ipynb
Labels: enhancement

#2252 Added PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#2254 feat: create CONTRIBUTING.md
  CONTRIBUTING.md
  README_template.md
Labels: hacktoberfest

#2260 feat: Update README.md CONTRIBUTING.md
  CONTRIBUTING.md
  README_template.md
Labels: enhancement

#2265 Fix the certificate name generated on PR merge
  .github/workflows/generate_certificate.yaml
Labels: bug

#2271 2255 matplotlib create piechart
  Matplotlib/Matplotlib_Create_Piechart.ipynb
Labels: hacktoberfest

#2288 feat(Buffer): Add Create draft
  Buffer/Buffer_Create_draft.ipynb
Labels: enhancement

#2286 OpenAI - Act as a customer
  OpenAI/OpenAI_Act_as_a_Customer.ipynb
Labels: hacktoberfest

#2287 feat: 2281 reddit search
  Reddit/Reddit_Search.ipynb
Labels: hacktoberfest

#2293 2270 appwrite user authentication
  Appwrite/Appwrite_User_Authentication.ipynb
Labels: enhancement, hacktoberfest

#2299 feat: Trello - Delete cards
  Trello/Trello_Delete_Cards.ipynb
Labels: enhancement, hacktoberfest-accepted

#2313 Python: Download webpage as pdf
  Python/Python_Download_Webpage_as_PDF.ipynb
Labels: enhancement

#2304 fix: removed unused table cols and added column preprocessor func
  Worldometer/Worldometer_World_population_evolution_and_projections.ipynb
Labels: bug

#2302 Medium-Publish article from markdown file
  Medium/Medium_Publish_article_from_Mardown_file.ipynb
Labels: enhancement, hacktoberfest

#2307 Update README_template.md
  CONTRIBUTING.md
  README_template.md
Labels: documentation

#2324 feat: plot wireframe using matplotlib
  Matplotlib/Matplotlib_Plot_Wireframe.ipynb
Labels: enhancement

#2311 fix: Added generic ffmpeg package helper and updated sample wav file
  .gitignore
  Python/Python_Convert_audiofile_from_wav_to_mp3.ipynb
Labels: bug

#2328 feat: initializing qa on sql databases with langchain notebook
  LangChain/LangChain_Perform_QA_on_SQL_Databases.ipynb
Labels: enhancement, hacktoberfest

#2332 2295 google drive create shareable public link
  Google Drive/Google_Drive_Create_shareable_public_link.ipynb
Labels: enhancement, hacktoberfest

#2321 feat: LinkedIn - Send connections to Google Sheets spreadsheet
  LinkedIn/LinkedIn_Get_connections_from_network.ipynb
  LinkedIn/LinkedIn_Send_connections_to_Google_Sheets_spreadsheet.ipynb
Labels: enhancement, hacktoberfest
